### ISSUE TITLE
Adicionar campo “observações” no site

### ISSUE THREAD

**Issue by cuducos** [InternetSemLimites/InternetSemLimites.github.io#12]
- informação vem na propriedade `provider.other`
- contém informações como cidades de cobertura, empresarial e/u residencial etc.
- sugestão: um parágrafo simples (sem caps mas fonte igual ao _PROVEDORES_) logo embaixo do nome do provedor

**Comment by cuducos** [comment]
@leomeloxp Não dei um merge do c44458a no _develop_ pq fiquei meio perdido com o `deploy.sh`… tu faz isso?

**Comment by leomeloxp** [comment]
@cuducos done 👍
