### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by cuducos** [InternetSemLimites/InternetSemLimites.github.io#9]
@kazzkiq Tu que tem os vetores do logo… não consegue criar algo que fique bom em baixa resolução para a gente usar de _favicon_? Muito obrigado

**Comment by kazzkiq** [comment]
Opa, tem sim!

Como não sei qual tamanhos exatamente você precisa eu exportei desde o menor padrão até os ícones para Smartphones (16x16px -- 512x512px)

Segue...

#### [Favicons_InternetSemLimites.zip](https://github.com/InternetSemLimites/InternetSemLimites.github.io/files/226679/Favicons_InternetSemLimites.zip)

**Comment by leomeloxp** [comment]
Valeu @kazzkiq. Já estão no site 👍

Dica: Para gerar os favicons, você pode usar o http://www.favicon-generator.org/ - Ele cria as imagens e dá as tags de HTML também, aí é só Ctrl+C, Ctrl+V.
